version: "3"

services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: server
    # image: dalau6/web2
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./server:/code

    ports:
      - "8000:8000"
    # environment:
    #   - SECRET_KEY=changemeinprod
    depends_on:
      - db
  #     - scrapy

  # scrapy:
  #   build: ecrawl
  #   command: scrapyd

  #   volumes:
  #     - ./ecrawl:/code
  #   ports:
  #     - 6800:6800
  #   depends_on:
  #     - db

  # cron:
  #   build: cron
  #   command: cron -f

  #   volumes:
  #     - ./cron:/code
  #   depends_on:
  #     - db

volumes:
  postgres_data:
